spring:
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    baseline-on-migrate: ${SPRING_FLYWAY_BASELINE_ON_MIGRATE:false}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}

springdoc:
  api-docs:
    enabled: ${SPRINGDOC_API_DOCS_ENABLED:false}
  swagger-ui:
    enabled: ${SPRINGDOC_SWAGGER_UI_ENABLED:false}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,prometheus}
  endpoint:
    health:
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:never}

smartcloset:
  security:
    jwt:
      secret: "${JWT_SECRET:}"
    refresh-token:
      cookie:
        secure: ${REFRESH_TOKEN_COOKIE_SECURE:true}
        same-site: "${REFRESH_TOKEN_COOKIE_SAME_SITE:None}"
    oauth2:
      state-cookie:
        secure: ${OAUTH_STATE_COOKIE_SECURE:true}
        same-site: "${OAUTH_STATE_COOKIE_SAME_SITE:None}"
